### PR TITLE
Test Release 2022 10 25

### PR DESCRIPTION
**Pull request by ghost**
Test Release 2022 10 25

### CODE REVIEW

**Comment by ghost** [comment]
@dosumis, I ran the release using `sh run.sh make prepare_release -B` and it appeared to wipe out the terms I added to efo_import.owl.

**Comment by dosumis** [comment]
I hope you committed first.

**Comment by ghost** [comment]
> I hope you committed first.

https://github.com/kharchenkolab/cap_ontology/pull/5/commits/cc35df5385220c1ede943d3fc147ccd27e525d66
https://github.com/kharchenkolab/cap_ontology/pull/5/commits/9e75a75b5542391468360cc40e92409339bf4db0

**Comment by ghost** [comment]
Replaced by https://github.com/kharchenkolab/cap_ontology/pull/6.

**Pull request closed without merging**
